-- Migration number: 0008 	 2026-08-30T23:53:17.392Z

ALTER TABLE user ADD COLUMN banned INTEGER;
ALTER TABLE user ADD COLUMN banReason TEXT;
ALTER TABLE user ADD COLUMN banExpires DATE;

ALTER TABLE session ADD COLUMN impersonatedBy TEXT;


