#!/bin/sh
set -e

case "$1" in
  purge)
    rm -rf /etc/monitoredu
    ;;
  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    if [ -d /run/systemd/system ]; then
      systemctl daemon-reload >/dev/null 2>&1 || true
    fi
    ;;
esac

exit 0
